---
title: "3_3st_HMM"
author: "Dennis Kim"
date: "2025-01-08"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)
library(mitools)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
oryx.2018 <- readRDS(here::here("data", "04.04.2025_hourly_final_preHMM_dataset.Rdata"))
oryx.2018 <- oryx.2018 %>% mutate(death = ifelse(death == 5, 3, death))
# remove everything before the dash in ID columns
oryx.2018$ID <- sub("-.*", "", oryx.2018$ID)

# ensure it is arrange with time per ID
oryx.2018 <- oryx.2018 %>% group_by(ID) %>% arrange(ID, time) %>% ungroup() %>% as.data.frame()
oryx.2018
```

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(oryx.2018, type = "UTM", covNames = c("shrub", "time_since_release"))

# check the hmm dataset
head(data_hmm, 10)
```

# Non-constrained 3-state HMM

null model without any restriction
```{r 5 state hmm covariates}
# number of states 
nbStates <- 3

# label states
stateNames <- c("1" = "S","2" = "I","3" = "D")

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# Initial parameters
# (step mean for state 1, step mean for state 2, step mean for state N so on... same for step SD s1, step SD s2) and (angle concentration s1, angle concentration s2)
Par0_3s <- list(step = c(1800, 315, 4,   # step means
                         1050, 365, 4),  # step sds
                angle = c(-0.03, 0.07, pi,  # angle means
                          1.5, 0.08, 0.4) # angle concentrations
               )

# Specify whether to estimate angle means
estAngleMean <- list(angle = TRUE)

# only constraining the death so that it can be an observing state 
fixbeta0 <-  matrix(c( # S: 1->2          1->3                
                            NA, NA, NA,    NA, NA, NA,   
                      # I: 2->1          2->3                  
                             NA, NA, NA,   NA, NA, NA,     
                      # D: 3->1                3->2               
                            -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6
                      ), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar0 <- list(beta = fixbeta0)

# Fit an unconstrained model
hmm <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_3s,
                          fixPar = fixPar0,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          #knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm

# save the hmm output 
readr::write_rds(hmm, path = here("data", "04.07.2025.3s_M1.Rdata"))
```

save the viberti 1
```{r state spatial visualization}
states <- momentuHMM::viterbi(hmm)
data_hmm1 <- data.frame(data_hmm)
data_hmm1$states <- states
data_hmm1$states <- factor(states, levels = c("1", "2", "3"))

data_hmm1

# save the rds file for the state sequences 
readr::write_rds(data_hmm1, path = here("data", "04.07.2025.3s_M1_viberti.Rdata"))
```

# Constrained 3-state HMM
```{r constrained 3states}
# make sure the transition between resting to death for shrub cover effects also 0 -- independent. 
fixbeta <-  matrix(c( # S: 1->2          1->3                
                            NA, NA, NA,   -1e6, -1e6, -1e6,   
                      # I: 2->1          2->3                  
                            -1e6, -1e6, -1e6,   NA, NA, NA,     
                      # D: 3->1                3->2               
                            -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6
                      ), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)

# Fit a constrained model
hmm2 <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_3s,
                          fixPar = fixPar,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          #knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm2

# save the rds file for the state sequences 
#readr::write_rds(hmm2, path = here("data", "04.07.2025.3s_M2.Rdata"))
```

save the viberti 2
```{r state spatial visualization}
states <- momentuHMM::viterbi(hmm2)
data_hmm2 <- data.frame(data_hmm)
data_hmm2$states <- states
data_hmm2$states <- factor(states, levels = c("1", "2", "3"))

data_hmm2

# save the rds file for the state sequences 
readr::write_rds(data_hmm2, path = here("data", "04.07.2025.3s_M2_viberti.Rdata"))
```

# constrained model with known states
```{r cs known states}
# Fit a constrained model
hmm3 <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_3s,
                          fixPar = fixPar,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm3

# save the rds file for the state sequences 
readr::write_rds(hmm3, path = here("data", "04.07.2025.3s_M3.Rdata"))
```


# Footer
```{r footer}
sessionInfo()
```