---
title: "3b.HMM_m2_shrub_Ndeath"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)
library(mitools)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
oryx <- readr::read_rds(here::here("data/HMM", "HMM_prep_data_m2.Rdata"))

oryx 
```

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(oryx, type = "UTM", covNames = "shrub")

# check the hmm dataset
head(data_hmm, 10)
```

# model fitting - a 5-state HMM

model
```{r 5 state hmm covariates}
# number of states 
nbStates <- 5

# label states
stateNames <- c("1" = "NE","2" = "NR","3" = "IE","4" = "IR","5" = "D")

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# Initial parameters
# (step mean for state 1, step mean for state 2, step mean for state N so on... same for step SD s1, step SD s2) and (angle concentration s1, angle concentration s2)
Par0_5s <- list(step = c(400, 50, 250, 50, 4,   # step means
                         400, 50, 250, 50, 4),  # step sds
                angle = c(0, pi, 0, pi, pi,  # angle means
                          0.05, 0.1, 0.01, 0.1, 0.001) # angle concentrations
               )

# Specify whether to estimate angle means
estAngleMean <- list(angle = TRUE)

# constrain transition probabilities - fix the transition probability matrix to prevent some of the transitions 
#we set to NA the columns of unconstrained transition probabilities, and we again fix the intercept of the other columns to a large negative number (here -1e6) to set the corresponding transition probabilities to be virtually zero (i.e., impossible transition). 

# make sure the transition between resting to death for shrub cover effects also 0 -- independent. 
fixbeta <-  matrix(c( # NE: 1->2          1->3            1->4          1->5
                            NA, NA,       -1e6, -1e6,     -1e6, -1e6,   -1e6, -1e6,
                      # NR: 2->1          2->3            2->4          2->5
                            NA, NA,       -1e6, -1e6,     NA, NA,       NA, 0,
                      # IE: 3->1          3->2            3->4          3->5
                            -1e6, -1e6,   -1e6, -1e6,     NA, NA,       -1e6, -1e6,
                      # IR: 4->1          4->2            4->3          4->5  
                            -1e6, -1e6,   -1e6, -1e6,     NA, NA,       NA, 0,
                      # D: 5->1           5->2            5->3          5->4
                            -1e6, -1e6,   -1e6, -1e6,     -1e6, -1e6,   -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)

# Fit a 5-state HMM
hmm <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_5s,
                          fixPar = fixPar,
                          formula = ~shrub,
                          estAngleMean = estAngleMean,
                          knownStates=data_hmm$death,
                          stateNames = stateNames)
```

model visualization - hmm
```{r hmm model output}
# Print parameter estimates
hmm

# save the hmm output 
saveRDS(hmm, "hmm_m4_output.rds")
#hmm <- readr::read_rds(here::here("data/hmm_real_outputs", "pool_hmm_shrub_ta.rds"))
```

```{r hmm visualization}
# Plot estimated distributions and state-coloured tracks
plot(hmm, breaks = 20, animals = 1, ask = FALSE)
```

save the plots as a pdf
```{r example, echo=FALSE, results='hide'}
pdf("HMM_m4.pdf")
plot(hmm, breaks = 20, ask=FALSE)
dev.off()
```

# estimated whole step length visauzliation 

```{r estimated sl2}
colours.states <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black")

x <- seq(0, 8000, length=1000)

meanNE <- hmm$mle$step[1,1]
sdNE <- hmm$mle$step[2,1] 

meanNR <- hmm$mle$step[1,2]
sdNR <- hmm$mle$step[2,2]  

meanIE <- hmm$mle$step[1,3]
sdIE <- hmm$mle$step[2,3]  

meanIR <- hmm$mle$step[1,4] 
sdIR <- hmm$mle$step[2,4]

meanD <- hmm$mle$step[1,5]
sdD <- hmm$mle$step[2,5]

sh <- function(mean, sd) { return(mean^2 / sd^2) }
sc <- function(mean, sd) { return(sd^2 / mean) }

y_NE <- dgamma(x, shape = sh(meanNE,sdNE), scale = sc(meanNE,sdNE))
y_NR <- dgamma(x, shape = sh(meanNR,sdNR), scale = sc(meanNR,sdNR))
y_IE <- dgamma(x, shape = sh(meanIE,sdIE), scale = sc(meanIE,sdIE))
y_IR <- dgamma(x, shape = sh(meanIR,sdIR), scale = sc(meanIR,sdIR))
y_D <- dgamma(x, shape = sh(meanD,sdD), scale = sc(meanD,sdD))

# combine densities in a single dataframe for more convenient plotting
df.y_NE <- data.frame(dens=y_NE, state="NE", x=x)
df.y_NR <- data.frame(dens=y_NR,  state="NR", x=x)
df.y_IE <- data.frame(dens=y_IE,  state="IE", x=x)
df.y_IR <- data.frame(dens=y_IR,  state="IR", x=x)
df.y_D <- data.frame(dens=y_D,  state="D", x=x)

cmb <- rbind(df.y_NE, df.y_NR, df.y_IE, df.y_IR, df.y_D)
cmb %>% summary()

# reorder factor levels so "total" appears bottom of the legend
cmb$state <- factor(cmb$state, levels = c("NE", "NR", "IE", "IR", "D"))

#cmb <- cmb %>%
  #filter_all(all_vars(is.finite(.)))

# plot distributions
ggplot() +
  geom_line(data=cmb,aes(x=x,y=dens,colour=state,linetype=state), size=1) +
  scale_colour_manual(values=c(colours.states)) +
  scale_linetype_manual(values=c("solid","solid","solid","solid", "dotted")) +
  #scale_y_continuous(limits=c(0,0.005)) +
  #scale_x_continuous(limits=c(0,2000)) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  ylab("Density") +
  xlab("Step (m)")+
  facet_wrap(~state, scales = "free")
```

save the sequence plot
```{r state spatial visualization}
states <- momentuHMM::viterbi(hmm)

data_hmm$states <- states

data_hmm$states <- factor(states, levels = c("1", "2", "3", "4", "5"))

data_hmm %>% filter(states == 5) %>% distinct(ID, states)

data_hmm

# save the rds file for the state sequences 
saveRDS(data_hmm, "HMM_m4_sequence.rds")
```

# Footer
```{r footer}
sessionInfo()
```