---
title: "4b.figure4"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)
library(collapse)
library(naniar)

# visualization 
library(ggplot2)
library(patchwork)
library(momentuHMM)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
m2 <- readr::read_rds(here::here("data/HMM_outputs", "hmm_m2_output.rds"))
```

# estimated whole step length visauzliation 

## model 2
```{r model 2}
meanNE <- m2$mle$step[1,1]
sdNE <- m2$mle$step[2,1] 

meanNR <- m2$mle$step[1,2]
sdNR <- m2$mle$step[2,2]  

meanIE <- m2$mle$step[1,3]
sdIE <- m2$mle$step[2,3]  

meanIR <- m2$mle$step[1,4] 
sdIR <- m2$mle$step[2,4]

meanD <- m2$mle$step[1,5]
sdD <- m2$mle$step[2,5]

y_NE <- dgamma(x, shape = sh(meanNE,sdNE), scale = sc(meanNE,sdNE))
y_NR <- dgamma(x, shape = sh(meanNR,sdNR), scale = sc(meanNR,sdNR))
y_IE <- dgamma(x, shape = sh(meanIE,sdIE), scale = sc(meanIE,sdIE))
y_IR <- dgamma(x, shape = sh(meanIR,sdIR), scale = sc(meanIR,sdIR))
y_D <- dgamma(x, shape = sh(meanD,sdD), scale = sc(meanD,sdD))

# combine densities in a single dataframe for more convenient plotting
df.y_NE <- data.frame(dens=y_NE, state="NE", x=x)
df.y_NR <- data.frame(dens=y_NR,  state="NR", x=x)
df.y_IE <- data.frame(dens=y_IE,  state="IE", x=x)
df.y_IR <- data.frame(dens=y_IR,  state="IR", x=x)
df.y_D <- data.frame(dens=y_D,  state="D", x=x)

cmb <- rbind(df.y_NE, df.y_NR, df.y_IE, df.y_IR, df.y_D)
cmb %>% summary()

# reorder factor levels so "total" appears bottom of the legend
cmb$state <- factor(cmb$state, levels = c("NE", "NR", "IE", "IR", "D"))

#cmb <- cmb %>%
  #filter_all(all_vars(is.finite(.)))

# plot distributions
step_m2 <- ggplot() +
  geom_line(data=cmb,aes(x=x,y=dens,colour=state,linetype=state), size=1) +
  scale_colour_manual(values=c(colours.states)) +
  scale_linetype_manual(values=c("solid","solid","solid","solid", "dotted")) +
  #scale_y_continuous(limits=c(0,0.005)) +
  #scale_x_continuous(limits=c(0,2000)) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45)) +
  facet_wrap(~state, scales = "free")+
  ylab("Density") +
  xlab("Step (m)")

step_m2
```

combine the plots 
```{r combine the plots}
# combine the figures 
#grid <- cowplot::plot_grid(fig3a, fig3b, nrow = 1, rel_widths = c(1/3,2/3), align = "h")

step_m2  
```

# Footer
```{r footer}
sessionInfo()
```