---
title: "3d.figure5"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)
library(collapse)
library(naniar)

# visualization 
library(ggplot2)
library(patchwork)
library(momentuHMM)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
m2 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m3_sequence.rds"))

m2 %>% mutate(year = year(time)) %>% distinct(year)
```

list of infection stats per id
```{r list of status}
m2.2 <- m2 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m2.2
```

add body condition index 
```{r body condition index}
# read the body condition data 
body_condition <- read.csv(here::here("data", "oryx_individual_field_data_122322.csv"))

# only select the columns that are applicable to the data 
body_condition <- body_condition %>% dplyr::select(datetime, animalID, lat, long, body_condition)

# filter the data with non-NAs for body condition values 
body_condition <- body_condition[complete.cases(body_condition[, 5]),]
body_condition

# change the column name of the body condition same as the original tracking data 
colnames(body_condition) <- c("date", "masterID", "lat", "long", "body_condition")

# select the healthy individuals for our cases 
BC <-
  body_condition %>% filter(
    masterID %in% unique(m2.2$masterID)
  )

# create julian dates and week id for the BC data
BC <- BC %>%
  mutate(julian = yday(date),
         week = week(date)) 

# calculate the average body condition value based on each duplicated week
average.week.BC <- BC %>% group_by(masterID, week) %>% 
  mutate(avg.bc = mean(body_condition)) %>% 
  dplyr::select(week, avg.bc) %>% 
  distinct()

# join the data
m2.3 <- m2.2 %>% left_join(average.week.BC, by = c("masterID", "week"))
  
# only select complete data with body condition
m2.3 <- m2.3 %>% filter(!is.na(avg.bc)) %>% 
  mutate(c_avg_BC = ifelse(avg.bc < 4, "under", ifelse(avg.bc < 7, "optimal", "over")) %>% as.factor(.))

colnames(m2.3)[12] <- "state"

m2.3 %>% dplyr::filter(cause_of_death %in% c("Dead", "Dead_infected")) 
```

# sequence over time 

model1: visualization to HMM state sequence over time 
```{r model1 state time visualization}
m2.4 <- m2.3 %>% dplyr::filter(cause_of_death %in% c("Dead_infected"))
m2.4 %>% distinct(ID)

# relevel the factor
#m2.4$ID <- factor(m2.4$ID, 
#                     levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "17", "18", "20", "21", "23", "24", "25", "26", "29", #"31", "36", "37", "39", "41", "42", "44", "47", "48", "51", "52", "53", "55", "56", "57", "58", "61", "65", "66", "68"))

# get most frequent values per group 
m2.5 <- m2.4 %>% 
  # add a column n with count by categories
  add_count(ID, julian, state, c_avg_BC) %>% 
  # select max or first occurrence by ID 
  group_by(ID, julian) %>% 
  # keep only first TRUE
  mutate(majority_state= state[n == max(n)][1],
         majority_bc = c_avg_BC[n == max(n)][1]) %>% 
  # do not keep temp var 
  dplyr::select(ID, masterID, majority_state, majority_bc, julian, time)

m2.5

# change the column names 
colnames(m2.5) <- c("ID", "masterID",  "state", "bc", "julian", "time")
m2.6 <- m2.5 %>% distinct()
m2.6
 
# last slice list 
whole_last_n_m2 <- m2.6 %>% group_by(ID) %>% slice_tail() %>% ungroup()
whole_last_n_m2 

# death value for each individual per model
death_m2 <- m2 %>% filter(states == 5) %>% distinct(ID)

whole_last_n_m2 <- whole_last_n_m2 %>% mutate(state = ifelse(ID %in% death_m2$ID, 5 , state))
whole_last_n_m2$state <- factor(whole_last_n_m2$state)
```

```{r model2 visualizations}
m2.6  <- m2.6 %>% ungroup() 
m2.6 <- m2.6 %>% filter(!masterID == "B69F")
whole_last_n_m2 <- whole_last_n_m2 %>% ungroup()
whole_last_n_m2 <- whole_last_n_m2 %>% filter(!masterID == "B69F")

# actual tested date 
test_data <- m2.6 %>% distinct(ID, masterID)
test_data$test_date <- c(265, 266, 269, 267, 265, 267, 265, 265)
```

set
```{r numbers}
test_data$ID <- as.numeric(as.character(test_data$ID))
m2.6$ID <- as.numeric(as.character(m2.6$ID))
whole_last_n_m2$ID <- as.numeric(as.character(whole_last_n_m2$ID))

test_data$id <- c(1, 2, 3, 4, 5, 6, 7, 8)

m2.6 <- m2.6 %>%
  mutate(id = case_when(
    ID == 5  ~ 1,
    ID == 7  ~ 2,
    ID == 10 ~ 3,
    ID == 24 ~ 4,
    ID == 33 ~ 5,
    ID == 40 ~ 6,
    ID == 51 ~ 7,
    ID == 52 ~ 8,
    TRUE     ~ NA_integer_
  ))

whole_last_n_m2 <- whole_last_n_m2 %>%
  mutate(id = case_when(
    ID == 5  ~ 1,
    ID == 7  ~ 2,
    ID == 10 ~ 3,
    ID == 24 ~ 4,
    ID == 33 ~ 5,
    ID == 40 ~ 6,
    ID == 51 ~ 7,
    ID == 52 ~ 8,
    TRUE     ~ NA_integer_
  ))
```

```{r figure visualization}
# Define the mapping from ID values to desired labels
id_labels <- c(
  "1" = "5",
  "2" = "7",
  "3" = "10",
  "4" = "24",
  "5" = "33",
  "6" = "40",
  "7" = "51",
  "8" = "52"
)

ggplot() +
  geom_errorbar(data = test_data, 
                aes(x = test_date, ymin = id-0.2, ymax = id+0.2), color="red", width=0, size=1) +
  geom_point(data = m2.6, aes(x = julian, y = id, color = state), size = 2) +
  geom_point(data = whole_last_n_m2, aes(x = julian, y = id, color = state, shape = bc), size = 2.5) +
  scale_y_continuous(name = "ID", 
                     labels = function(x) id_labels[as.character(x)],  # Use custom labels based on ID mapping
                     breaks = m2.6$id) +  # Adjust breaks based on your actual data
  
  scale_color_manual(name = "State",
                     values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D")) +
  
  scale_shape_manual(name = "Body Condition",
                     values = c(15, 17, 19),
                     na.value = 16,
                     labels = c("Under", "Optimal", "Over")) +
  
  theme(axis.text = element_text(size = 7)) +
  xlab("Julian") +
  ylab("ID")
```


# Footer
```{r footer}
sessionInfo()
```