---
title: "6a.appendix"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)

# call environmental data
library(terra)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
m2 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m2_sequence.rds"))

# change the col name to "state"
names(m2)[12] <- "state"

m2 <- m2 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m2
```

list of infection stats per id
```{r list of status}
m2 %>% distinct(ID) 
```

visualize 
```{r visualization}
map_1 <- m2 %>% filter(ID %in% c(1, 2, 3, 4, 5, 6, 8, 9, 10))
map_2 <- m2 %>% filter(ID %in% c(11, 12, 13, 14, 15, 16, 17, 18, 19 ,20))
map_3 <- m2 %>% filter(ID %in% c(21, 22, 23, 24, 25, 26, 27, 28, 29, 30))
map_4 <- m2 %>% filter(ID %in% c(31, 32, 33, 34, 35, 36, 37, 38, 39, 40))
map_5 <- m2 %>% filter(ID %in% c(41, 42, 43, 44, 45, 46, 47, 48, 49, 50))
map_6 <- m2 %>% filter(ID %in% c(51, 52, 53, 54, 55, 56, 57, 58, 59, 60))
map_7 <- m2 %>% filter(ID %in% c(61, 62, 63, 64, 65, 66, 67, 68))

# map 1
whole_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
whole_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
whole_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
whole_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 5
whole_vis_5 <- ggplot(map_5, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 6 
whole_vis_6 <- ggplot(map_6, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 7
whole_vis_7 <- ggplot(map_7, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

save the plots as a pdf
```{r pdf whole example, echo=FALSE, results='hide'}
pdf("appendixA.pdf")
whole_vis_1
whole_vis_2
whole_vis_3
whole_vis_4
whole_vis_5
whole_vis_6
whole_vis_7
dev.off()
```

visualize with free scale 
```{r free vis}
# map 1
free_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
free_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
free_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
free_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 5
free_vis_5 <- ggplot(map_5, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 6
free_vis_6 <- ggplot(map_6, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 7
free_vis_7 <- ggplot(map_7, mapping = aes(x, y, col = state, group = ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

```{r pdf free example, echo=FALSE, results='hide'}
pdf("appendixB.pdf")
free_vis_1
free_vis_2
free_vis_3
free_vis_4
free_vis_5
free_vis_6
free_vis_7
dev.off()
```

# Footer
```{r footer}
sessionInfo()
```