---
title: "4b.figure4"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)
library(collapse)
library(naniar)

# visualization 
library(ggplot2)
library(patchwork)
library(momentuHMM)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
m1 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m1_sequence.rds"))
m2 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m2_sequence.rds"))

# change the col name to "state"
names(m1)[11] <- "state"
names(m2)[12] <- "state"

m1
m2
```

list of infection stats per id
```{r list of status}
m1.2 <- m1 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m2.2 <- m2 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m1.2 
m2.2 %>% filter(cause_of_death == "Dead" | cause_of_death == "Dead_infected") %>% distinct(ID, cause_of_death)
```

# model 1 
```{r model 1}
fig4_m1 <- m1.2 %>% filter(ID %in% c(10, 13, 18, 33))

# new facet label names for dose variable 
id.labs <- c("10" = "Dead Infected 10", 
             "13" =  "Dead 13", 
             "18" =  "Dead Infected 18", 
             "33" =  "Dead Infected 33")

fig4_m1

# same scale 
fig4a <- ggplot(fig4_m1, mapping = aes(x, y, col = state, group = ID))+
  geom_point(size = 0.7, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID,
             labeller = labeller(ID = id.labs))+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45),
        legend.position = "none"
        )+
  xlab("Longtidue")+
  ylab("Latitude")+
  ggtitle("(a)")

# free scale 
fig4c <- ggplot(fig4_m1, mapping = aes(x, y, col = state, group = ID))+
  geom_point(size = 0.5, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.01)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  facet_wrap(~ID,
             labeller = labeller(ID = id.labs),
             scales = "free",
             ncol = 2)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45),
        legend.position = "none")+
  xlab("Longtidue")+
  ylab("Latitude")+
  ggtitle("(c)")

fig4a
fig4c
```

# model 2 
```{r model 2}
fig4_m2 <- m2.2 %>% filter(ID %in% c(10, 13, 18, 33))

fig4_m2

# same scale 
fig4b <- ggplot(fig4_m2, mapping = aes(x, y, col = state, group = ID))+
  geom_point(size = 0.7, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~ID,
             labeller = labeller(ID = id.labs))+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45)
        )+
  xlab("Longtidue")+
  ylab("Latitude")+
  ggtitle("(b)")

# free scale 
fig4d <- ggplot(fig4_m2, mapping = aes(x, y, col = state, group = ID))+
  geom_point(size = 0.5, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.01)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  facet_wrap(~ID,
             labeller = labeller(ID = id.labs),
             scales = "free",
             ncol = 2)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45),
        legend.position = "none")+
  xlab("Longtidue")+
  ylab("Latitude")+
  ggtitle("(d)")

fig4b
fig4d
```


combine the plots 
```{r combine the plots}
# combine the figures 
#grid <- cowplot::plot_grid(fig3a, fig3b, nrow = 1, rel_widths = c(1/3,2/3), align = "h")

(fig4a | fig4b) /
(fig4c | fig4d)   
```

# Footer
```{r footer}
sessionInfo()
```