---
title: "3d.figure5"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)
library(collapse)
library(naniar)

# visualization 
library(ggplot2)
library(patchwork)
library(momentuHMM)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
m1 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m1_sequence.rds"))
m2 <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_m2_sequence.rds"))

m1 %>% mutate(year = year(time)) %>% distinct(year)
m2 %>% mutate(year = year(time)) %>% distinct(year)
```

list of infection stats per id
```{r list of status}
m1.2 <- m1 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m2.2 <- m2 %>% mutate(julian = lubridate::yday(time),
                            week = lubridate::week(time)) # create the week column

m1.2
m2.2
```

add body condition index 
```{r body condition index}
# read the body condition data 
body_condition <- read.csv(here::here("data", "oryx_individual_field_data_122322.csv"))

# only select the columns that are applicable to the data 
body_condition <- body_condition %>% dplyr::select(datetime, animalID, lat, long, body_condition)

# filter the data with non-NAs for body condition values 
body_condition <- body_condition[complete.cases(body_condition[, 5]),]
body_condition

# change the column name of the body condition same as the original tracking data 
colnames(body_condition) <- c("date", "masterID", "lat", "long", "body_condition")

# select the healthy individuals for our cases 
BC <-
  body_condition %>% filter(
    masterID %in% unique(m2.2$masterID)
  )

# create julian dates and week id for the BC data
BC <- BC %>%
  mutate(julian = yday(date),
         week = week(date)) 

# calculate the average body condition value based on each duplicated week
average.week.BC <- BC %>% group_by(masterID, week) %>% 
  mutate(avg.bc = mean(body_condition)) %>% 
  dplyr::select(week, avg.bc) %>% 
  distinct()

# join the data
m1.3 <- m1.2 %>% left_join(average.week.BC, by = c("masterID", "week"))
m2.3 <- m2.2 %>% left_join(average.week.BC, by = c("masterID", "week"))
  
# only select complete data with body condition
m1.3 <- m1.3 %>% filter(!is.na(avg.bc)) %>% 
  mutate(c_avg_BC = ifelse(avg.bc < 4, "under", ifelse(avg.bc < 7, "optimal", "over")) %>% as.factor(.))

m2.3 <- m2.3 %>% filter(!is.na(avg.bc)) %>% 
  mutate(c_avg_BC = ifelse(avg.bc < 4, "under", ifelse(avg.bc < 7, "optimal", "over")) %>% as.factor(.))

colnames(m1.3)[11] <- "state"
colnames(m2.3)[12] <- "state"

m1.3 %>% dplyr::filter(cause_of_death %in% c("Dead", "Dead_infected"))
m2.3 %>% dplyr::filter(cause_of_death %in% c("Dead", "Dead_infected")) 
```

# sequence over time 

model1: visualization to HMM state sequence over time 
```{r model1 state time visualization}
m1.4 <- m1.3 %>% dplyr::filter(cause_of_death %in% c("Dead", "Dead_infected"))
m1.4 %>% distinct(ID)

# relevel the factor
#m1.4$ID <- factor(m1.4$ID, 
#                    levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "17", "18", "20", "21", "23", "24", "25", "26", "29", #"31", "36", "37", "39", "41", "42", "44", "47", "48", "51", "52", "53", "55", "56", "57", "58", "61", "65", "66", "68"))

#m1.3$state <- as.numeric(m1.3$state) 
#m1.3$c_avg_BC <- as.numeric(m1.3$c_avg_BC)

# get most frequent values per group 
m1.5 <- m1.4 %>% 
  # add a column n with count by categories
  add_count(ID, julian, state, c_avg_BC) %>% 
  # select max or first occurrence by ID 
  group_by(ID, julian) %>% 
  # keep only first TRUE
  mutate(majority_state= state[n == max(n)][1],
         majority_bc = c_avg_BC[n == max(n)][1]) %>% 
  # do not keep temp var 
  dplyr::select(ID, majority_state, majority_bc, julian, time)

m1.5

# change the column names 
colnames(m1.5) <- c("ID", "state", "bc", "julian", "time")
m1.6 <- m1.5 %>% distinct()
m1.6

# last slice list 
whole_last_n_m1 <- m1.5 %>% group_by(ID) %>% summarise_all(last)
whole_last_n_m1

# death value for each individual per model
death_m1 <- m1 %>% filter(states == 5) %>% distinct(ID)

whole_last_n_m1 <- whole_last_n_m1 %>% mutate(state = ifelse(ID %in% death_m1$ID, 5 , state))
whole_last_n_m1$state <- factor(whole_last_n_m1$state)
whole_last_n_m1
```

```{r sequence figure5}
# visualize the trends 
#fig4 <- ggplot(m1.5, aes(x =julian, y = ID))+
#        geom_point(stat='identity', aes(color=state, shape = bc), size = 2)+
        #geom_line(stat = 'identity', aes(col=state), size = 1)+
#        scale_y_discrete("ID", 
#                          labels = as.character(m1.3$ID), 
#                          breaks = m1.3$ID#, 
                          #expand = expansion(mult = c(0, .02),add = c(1, 0))
#                          )+
#        scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
#                            labels = c("NE", "NR", "IE", "IR", "D"))+
#        scale_shape_manual(values = c(15, 17),
#                           na.value = 16,
#                           labels = c("Under", "Optimal")
#                          )+
#        theme_bw()+
#        xlab("julian")

fig4a_m1 <- ggplot() +
  geom_point(data = m1.6, aes(x = julian, y = ID, color = state), size = 2) +
  geom_point(data = whole_last_n_m1, aes(x = julian, y = ID, color = state, shape = bc), size = 2.5) +
  scale_y_discrete("ID", 
                   labels = as.character(m1.2$ID), 
                   breaks = m1.2$ID) +
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D")) +
  scale_shape_manual(values = c(15, 17, 19),
                     na.value = 16,
                     labels = c("Under", "Optimal", "Over")) +
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1),
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45),
        legend.position = "none"
        ) +
  xlab("Julian")+
  ggtitle("(a)")

fig4a_m1
```

model2: visualization to HMM state sequence over time 
```{r model2 state time visualization}
m2.4 <- m2.3 %>% dplyr::filter(cause_of_death %in% c("Dead", "Dead_infected"))
m2.4 %>% distinct(ID)

# relevel the factor
#m2.4$ID <- factor(m2.4$ID, 
#                     levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "17", "18", "20", "21", "23", "24", "25", "26", "29", #"31", "36", "37", "39", "41", "42", "44", "47", "48", "51", "52", "53", "55", "56", "57", "58", "61", "65", "66", "68"))

# get most frequent values per group 
m2.5 <- m2.4 %>% 
  # add a column n with count by categories
  add_count(ID, julian, state, c_avg_BC) %>% 
  # select max or first occurrence by ID 
  group_by(ID, julian) %>% 
  # keep only first TRUE
  mutate(majority_state= state[n == max(n)][1],
         majority_bc = c_avg_BC[n == max(n)][1]) %>% 
  # do not keep temp var 
  dplyr::select(ID, majority_state, majority_bc, julian, time)

m2.5

# change the column names 
colnames(m2.5) <- c("ID", "state", "bc", "julian", "time")
m2.6 <- m2.5 %>% distinct()
m2.6
 
# last slice list 
whole_last_n_m2 <- m2.6 %>% group_by(ID) %>% slice_tail() %>% ungroup()
whole_last_n_m2 

# death value for each individual per model
death_m2 <- m2 %>% filter(states == 5) %>% distinct(ID)

whole_last_n_m2 <- whole_last_n_m2 %>% mutate(state = ifelse(ID %in% death_m2$ID, 5 , state))
whole_last_n_m2$state <- factor(whole_last_n_m2$state)
```

```{r model2 visualizations}
# visualize the trends 
fig4a2 <- ggplot() +
  geom_point(data = m2.6, aes(x = julian, y = ID, color = state), size = 2) +
  geom_point(data = whole_last_n_m2, aes(x = julian, y = ID, color = state, shape = bc), size = 2.5) +
  scale_y_discrete("ID", 
                   labels = as.character(m2.6$ID), 
                   breaks = m2.6$ID) +
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D")) +
  scale_shape_manual(values = c(15, 17, 19),
                     na.value = 16,
                     labels = c("Under", "Optimal", "Over")) +
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1),
        panel.background = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45)
        )+
  xlab("Julian")+
  ggtitle("(b)")

fig4a2
```

combine the plots 
```{r combine the plots}
# combine the figures 
#grid <- cowplot::plot_grid(fig3a, fig3b, nrow = 1, rel_widths = c(1/3,2/3), align = "h")

fig4a_m1 | fig4a2 
```

# Footer
```{r footer}
sessionInfo()
```