---
title: "6.data_merge_BC"
author: "Dennis Kim"
date: "2022-12-28"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(here)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(amt)

options(width = 150)

# set knitr options 
opts_chunk$set(fig.width = 6, fig.height = 5, comment = NA)
```

# Read data 
```{r read in data}
# read the tracking data: healthy & infected individuals
health <- read.csv(here::here("data", "health_oryx_tmp_speed.csv"))
disease <- read.csv(here::here("data", "infect_oryx_tmp_speed.csv"))

# read the body condition data 
body_condition <- read.csv(here::here("data", "oryx_individual_field_data_122322.csv"))

# only select the columns that are applicable to the data 
body_condition <- body_condition %>% dplyr::select(datetime, animalID, lat, long, body_condition)

# filter the data with non-NAs for body condition values 
body_condition <- body_condition[complete.cases(body_condition[, 5]),]

summary(body_condition)
```

# merge the data 

## healthy individuals
```{r healthy merge}
# change the column name of the body condition same as the original tracking data 
colnames(body_condition) <- c("t_", "masterID", "y_", "x_", "body_condition")

# select the healthy individuals for our cases 
healthy.BC <- body_condition %>% filter(masterID == c("B72R35_W277F", "R14R28_Y70F", "R02B23_W88F", "N23B28_Y66F", "R52R29_B494F"))

# create julian dates and week id for the original data and BC data

health <- health %>% 
  mutate(
    julian = yday(t_),
    week = week(t_)
  )

healthy.BC <- healthy.BC %>% 
  mutate(
    julian = yday(t_),
    week = week(t_)
  ) 

# calculate the average body condition value based on each duplicated week
average.week.BC <- healthy.BC %>% group_by(week) %>% 
  mutate(avg.bc = mean(body_condition)) %>% 
  dplyr::select(week, avg.bc) %>% 
  distinct()

# join the data
health.df <- health %>% left_join(average.week.BC, by = c("week"))

# only select complete data with body condition
comp.health.df <- health.df %>% filter(!is.na(avg.bc))

comp.health.df %>% head()
```

```{r save the healthy body condition data}
# save the data 
#write.csv(comp.health.df, "healthy_inds_BC.csv")
```

Plot the data 
```{r alive plots}
# facet id plots
ggplot(comp.health.df, aes(x = x_,
                         y = y_))+ geom_point()+
  facet_wrap(~masterID, scales = "free")+
  ggtitle("Locations of alive/healthy individuals")
```

## Infected individuals
```{r h mergdisease}
# select the healthy individuals for our cases 
disease.BC <- body_condition %>% filter(masterID == c("R02M", "B05M", "R38F", "B49M"))

# create julian dates and week id for the original data and BC data
disease <- disease %>% 
  mutate(
    julian = yday(t_),
    week = week(t_)
  )

disease.BC <- disease.BC %>% 
  mutate(
    julian = yday(t_),
    week = week(t_)
  ) 

# calculate the average body condition value based on each duplicated week
average.disease.week.BC <- disease.BC %>% group_by(week) %>% 
  mutate(avg.bc = mean(body_condition)) %>% 
  dplyr::select(week, avg.bc) %>% 
  distinct()

# join the data
disease.df <- disease %>% left_join(average.disease.week.BC, by = c("week"))

# only select complete data with body condition
comp.disease.df <- disease.df %>% filter(!is.na(avg.bc))

comp.disease.df %>% head()
```

```{r save the infected body condition data}
# save the data 
#write.csv(comp.disease.df, "infected_inds_BC.csv")
```

Plot the data 
```{r alive plots}
# facet id plots
ggplot(comp.disease.df, aes(x = x_,
                         y = y_))+ geom_point()+
  facet_wrap(~masterID, scales = "free")+
  ggtitle("Locations of infected individuals")
```

# Footer
```{r footer}
sessionInfo()
```