---
title: "7.SSF_updated_sl_IF"
author: "Dennis Kim"
date: "2023-07-12"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(here)
library(tidyverse)
library(lubridate)
library(amt)
library(ggplot2)
library(broom)
library(jtools)
library(huxtable)
library(cowplot)
library(glmmTMB)
library(circular)
library(raster)
library(terra)
library(sp)
library(sf)
library(ggthemes)
options(width = 150)

# set knitr options 
opts_chunk$set(fig.width = 6, fig.height = 5, comment = NA)
```

# Read amt trk Data

Tracking amt trk data
```{r trk data}
# read the tracking data: R01M
ssfdat <- read_rds(here::here("data/finalized_data", "final_multi.Rdata"))
ssfdat <- ssfdat %>% dplyr::select(-c(NDVI, total_precipitation)) # remove the original NDVI extraction and precipitation
summary(ssfdat)
```

Bring environmental covariates
```{r env data}
# temperature
use.temp <- read_csv(here::here("data/env_data/temp", "used_pts_nearest_ERA5HourlyTemp.csv"))
random.temp <- read_csv(here::here("data/env_data/temp", "random_pts_nearest_ERA5HourlyTemp.csv"))

# leaf are index 
use.lai <- read_csv(here::here("data/env_data/leaf", "used_pts_nearest_MOD15A2H061_LAI_FPAR.csv"))
random.lai <- read_csv(here::here("data/env_data/leaf", "random_pts_nearest_MOD15A2H061_LAI_FPAR.csv"))

# NDVI
use.ndvi <- read_csv(here::here("data/env_data/ndvi_new", "used_pts_nearest_ndvi_timeAdj.csv"))
random.ndvi <- read_csv(here::here("data/env_data/ndvi_new", "random_pts_nearest_ndvi_timeAdj.csv"))

# GPP 
use.gpp <- read_csv(here::here("data/env_data/GPP", "used_pts_nearest_GPP_timeAdj.csv"))
random.gpp <- read_csv(here::here("data/env_data/GPP", "random_pts_nearest_GPP_timeAdj.csv"))
```

Change the colnames 
```{r used}
# use
use.temp <- use.temp %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t1_", "masterID","case_", "temp"))
use.lai <- use.lai %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:5), ~c("t1_", "masterID", "case_", "fpar", "lai"))
use.ndvi <- use.ndvi %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t1_", "masterID", "case_", "NDVI"))
use.gpp <- use.gpp %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t1_", "masterID", "case_", "GPP"))

# random
random.temp <- random.temp %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t2_", "masterID","case_", "temp"))
random.lai <- random.lai %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:5), ~c("t2_", "masterID", "case_", "fpar", "lai"))
random.ndvi <- random.ndvi %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t2_", "masterID", "case_", "NDVI"))
random.gpp <- random.gpp %>% dplyr::select(- c(x_, y_)) %>%  rename_with(.cols = c(1:4), ~c("t2_", "masterID", "case_", "GPP"))
```

divide the original ssfdat filtered by case
```{r data modification}
# ssf 
true_ssfdat <- ssfdat %>% dplyr::filter(case_ == "TRUE")
random_ssfdat <- ssfdat %>% dplyr::filter(case_ == "FALSE")

# used locations
## left join - length 192765
true_ssfdat1 <- true_ssfdat %>% left_join(use.temp, by = c("t1_", "masterID", "case_")) # temp
true_ssfdat2 <- true_ssfdat1 %>% left_join(use.lai, by = c("t1_", "masterID", "case_")) # LAI 
true_ssfdat3 <- true_ssfdat2 %>% left_join(use.gpp , by = c("t1_", "masterID", "case_")) # GPP
true_ssfdat4 <- true_ssfdat3 %>% left_join(use.ndvi , by = c("t1_", "masterID", "case_")) # NDVI

# random locations 
## left join - length 1927688
random_ssfdat1 <- random_ssfdat %>% left_join(random.temp[!duplicated(random.temp),], by = c("t2_", "masterID", "case_")) # temp
random_ssfdat2 <- random_ssfdat1 %>% left_join(random.lai[!duplicated(random.lai),], by = c("t2_", "masterID", "case_")) # LAI 
random_ssfdat3 <- random_ssfdat2 %>% left_join(random.gpp[!duplicated(random.gpp),] , by = c("t2_", "masterID", "case_")) # GPP
random_ssfdat4 <- random_ssfdat3 %>% left_join(random.ndvi[!duplicated(random.ndvi),] , by = c("t2_", "masterID", "case_")) # NDVI

# rbind the used and random locations 
final.ssfdat <- rbind(true_ssfdat4, random_ssfdat4)
# reformat the structure 
final.ssfdat <- final.ssfdat %>% group_by(masterID) %>% arrange(step_id_) %>% ungroup()
summary(final.ssfdat)
```

save the finalized data 
```{r save the finalized data}
#write_rds(final.ssfdat, path = here("data/finalized_data","finalize_ssfdat.Rdata"))
```

# Footer
```{r footer}
sessionInfo()
```
