---
title: "6.figure5"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)
library(caret)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)
library(patchwork)

options(width = 150)
```

Read in the prep data
```{r read in prep data}
# Simulation hmm output 
hmm <- readr::read_rds(here::here("data/HMM_outputs", "hmm_sim4_output.rds"))
hmm

actual_m_hmm <- readr::read_rds(here::here("data/HMM_outputs", "hmm_m4_output.rds"))
actual_m_hmm
```

transition probability
```{r tpm}
# get the estimation with 95 confidence intervals 
trProb <- CIbeta(hmm, alpha = 0.95)
trProb$beta

# convert it to df 
hmm_estimate_tpm <- data.frame(est = c(trProb$beta$est), se = c(trProb$beta$se), lower = c(trProb$beta$lower), upper = c(trProb$beta$upper))

hmm_estimate_tpm

# na omit
hmm_estimate_tpm <- hmm_estimate_tpm %>% filter(!est == -1e6)
hmm_estimate_tpm
hmm_estimate_tpm$param <- c("b0_12", "b1_12","b0_21", "b1_21", "b0_24", "b1_24", "b0_25", "b1_25", "b0_34", "b1_34", "b0_43", "b1_43", "b0_45", "b1_45")
hmm_estimate_tpm

# add true values 
hmm_estimate_tpm$true <- c(-0.7386564, -0.0558424, -1.81165344, -0.07995076, -7.3350253, 0.2128888, -9.083568, 0, -2.65275129, 0.06989157, -0.79625354, 0.03259497, -4.967093, 0)

hmm_estimate_tpm[is.na(hmm_estimate_tpm)] <- 0

# filter out only the beta 
hmm_estimate_tpm <- hmm_estimate_tpm[!grepl("5", hmm_estimate_tpm$param), ]
hmm_estimate_tpm <- hmm_estimate_tpm %>% mutate(group = c("b0", "b1", "b0", "b1", "b0", "b1", "b0", "b1", "b0", "b1"))
hmm_estimate_tpm

#save 
#saveRDS(hmm_estimate_tpm, "HMM_estimate_tpm_final.rds")
```

## plot1: paratmeter estimation with 95% confidence intervals - comparison 

```{r plot1}
# Create a custom labeller using named vectors
custom_labels <- c(b0 = "beta[0]", b1 = "beta[1]")

# Create a custom labeller for the x-axis
custom_x_labels <- c(
  "b0_12" = expression(beta[0] * "_12"),
  "b0_21" = expression(beta[0] * "_21"),
  "b0_24" = expression(beta[0] * "_24"),
  "b0_34" = expression(beta[0] * "_34"),
  "b0_43" = expression(beta[0] * "_43"),
  "b1_12" = expression(beta[1] * "_12"),
  "b1_21" = expression(beta[1] * "_21"),
  "b1_24" = expression(beta[1] * "_24"),
  "b1_34" = expression(beta[1] * "_34"),
  "b1_43" = expression(beta[1] * "_43")
)

fig9 <- ggplot(hmm_estimate_tpm, aes(x = factor(param), y = est, ymin = lower, ymax = upper, color = factor(param))) +
  geom_pointrange() +
  geom_point(data = hmm_estimate_tpm, aes(y = true), color = "black", shape = 17, size = 2) +
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        legend.position = "none") +
  facet_wrap(~ group, scales = "free_x", labeller = labeller(group = as_labeller(custom_labels, label_parsed))) +
  scale_x_discrete(labels = custom_x_labels)+
  labs(title = "(a)", x = "Transition Parameters", y = "Estimation")  # Set labels for axes and legend
  

fig9
```

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
sim_sequence <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_sim4_sequence.rds"))
colnames(sim_sequence)[7] <- "null_state"
sim_sequence 
```

# accuracy metrics 
```{r accuracy metrics}
# Function to calculate metrics
calculate_metrics <- function(actual, predicted, state) {
  # Create binary vectors for the current state
  actual_binary <- ifelse(actual == state, 1, 0)
  predicted_binary <- ifelse(predicted == state, 1, 0)
  
  # Confusion Matrix
  cm <- confusionMatrix(as.factor(predicted_binary), as.factor(actual_binary), positive = "1")
  
  # Extract metrics
  accuracy <- cm$overall["Accuracy"]
  precision <- cm$byClass["Precision"]
  recall <- cm$byClass["Recall"]
  F1 <- cm$byClass["F1"]
  
  return(data.frame(state = state, accuracy = accuracy, precision = precision, recall = recall, F1 = F1))
}

# Apply the function to each state
metrics <- bind_rows(lapply(unique(sim_sequence$null_state), function(state) {
  calculate_metrics(sim_sequence$null_state, sim_sequence$est_state, state)
}))

# View the calculated metrics
print(metrics)

metrics

# save accuracy metrics as RDS file for further analysis
saveRDS(metrics, "HMM_sim_accu_final_metrics.rds")
```


```{r accuracy matrix}
# Step 2: Create confusion matrix
conf_matrix <- table(sim_sequence$null_state, sim_sequence$est_state)
conf_matrix

# get the proportion to each state - precentage
# Convert the confusion matrix to percentages
conf_matrix_percentage <- prop.table(conf_matrix, margin = 1) * 100
conf_matrix_percentage
```

confusion matrix
```{r confusion matrix}
# make it to the dataframe
conf_matrix_df <- as.data.frame.matrix(conf_matrix_percentage)
rownames(conf_matrix_df) <- c("NE", "NR", "IE", "IR", "D")  # Assuming you know the row order matches these states
conf_matrix_df <- cbind(actual_state = rownames(conf_matrix_df), conf_matrix_df)
conf_matrix_df <- gather(conf_matrix_df, key = "estimated_state", value = "percentage", -actual_state)
conf_matrix_df

## change the factorized values names
conf_matrix_df <- conf_matrix_df %>%
  mutate(
    estimated_state = case_when(
      estimated_state == 1 ~ "NE",
      estimated_state == 2 ~ "NR",
      estimated_state == 3 ~ "IE",
      estimated_state == 4 ~ "IR",
      estimated_state == 5 ~ "D",
      TRUE ~ "Unknown"
    )
  )

## factorize the x and y axis columns 
conf_matrix_df$actual_state <- factor(conf_matrix_df$actual_state, levels = c("NE", "NR", "IE","IR", "D"))
conf_matrix_df$estimated_state <- factor(conf_matrix_df$estimated_state, levels = c("NE", "NR", "IE","IR", "D"))

conf_matrix_df
```

```{r vis}
# Plot the confusion matrix
fig10 <- ggplot(data = conf_matrix_df, aes(x = estimated_state, y = reorder(actual_state, -as.numeric(actual_state)), fill = percentage)) +
  geom_tile(color = "black") +  # Add tiles with black border
  scale_fill_gradient2(
    low = "white", high = "#b30000",  # Set colors for gradient
    limits = c(0, 100),  # Correct the limits for percentage data
    space = "Lab",
    name = "Percentage"
  ) +
  coord_fixed(ratio = 1) +  # Keep aspect ratio of tiles 1 to ensure they are square
  geom_text(aes(label = paste0(round(percentage, 1), "%")), color = "black", size = 4) +  # Correct the reference to 'percentage'
  scale_x_discrete(position = "top") +  # Set x-axis labels to the top
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1),
    panel.background = element_blank()
  ) +
  labs(title = "(b)", x = "Estimated State", y = "Actual State", fill = "Percentage")  # Set labels for axes and legend

fig10
```

Put them together
```{r path work}
(fig9 + fig10)+ plot_layout(guides = "collect")
```

# Footer
```{r footer}
sessionInfo()
```
