---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)

# call environmental data
library(terra)

# analysis
library(adehabitatLT)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/hmm_visualization_data", "pool_hmm_sequence.rds"))
ind_df <- readr::read_rds(here::here("data/hmm_visualization_data", "npool_hmm_sequence.rds"))
#ran_df <- readr::read_rds(here::here("data/hmm_visualization_data", "whole_hmmTMB_sequence.rds"))

# only select the columns that we will use 
whole_df <- whole_df %>% dplyr::select("ID", "states", "x", "y")
ind_df <- ind_df %>% dplyr::select("ID", "states", "x", "y")

# change the col name to "state"
names(whole_df)[2] <- "state"
names(ind_df)[2] <- "state"

# create group names 
whole_df$group <- "pool"
ind_df$group <- "non_pool"
#ran_df$group <- "hmmTMB"

# bind two data 
all_df <- rbind(whole_df, ind_df#, ran_df
                )

# relevel the group 
all_df$group <- factor(all_df$group, level = c("pool", "non_pool"#, "hmmTMB"
                                               ))

all_df
```

```{r master id}
# get the master ID


#master_id <- readr::read_rds(here::here("data/finalized_data", "rainy_trk.Rdata"))
#master_id <- master_id %>% dplyr::select(masterID, num_id) %>% distinct(.)
#whole_id <- whole_df %>% dplyr::select(ID) %>% distinct()
#colnames(master_id) <- c("masterID", "ID")
#master_id$ID <- factor(master_id$ID)
#no_whole_id <- anti_join(master_id, whole_id, by = "ID")
#true_master_id <- master_id %>% filter(!ID %in% no_whole_id$ID)

#test_whole_sequence <- whole_df %>% left_join(., true_master_id, by = "ID")
#test_whole_sequence <- test_whole_sequence %>% dplyr::select("masterID", "ID", "x", "y", "time", "states")

#test_whole_sequence <- test_whole_sequence %>% mutate(status = ifelse(test_whole_sequence$ID %in% i_list, "infected", ifelse(test_whole_sequence$ID %in% n_list, "Noinfected", "Unknown")))

test_whole_sequence %>% distinct(masterID)

# save the data
#saveRDS(test_whole_sequence, "pool_hmm_sequence_list.rds")
```


list of infection stats per id
```{r list of status}
n_oryx <- read_rds(here::here("data/ssf_data", "n_ssf_oryx.rds"))
u_oryx <- read_rds(here::here("data/ssf_data", "u_ssf_oryx.rds"))
i_oryx <- read_rds(here::here("data/ssf_data", "i_ssf_oryx.rds"))

n_list <- unique(n_oryx$ID)
u_list <- unique(u_oryx$ID)
i_list <- unique(i_oryx$ID)

rm(n_oryx, u_oryx, i_oryx)

# create a new ID
all_df1 <- all_df %>% mutate(status = ifelse(all_df$ID %in% i_list, "i", ifelse(all_df$ID %in% n_list, "n", "u")))

all_df1$new_ID <- paste(all_df1$status, all_df1$ID, sep = "_")
all_df1
```

visualize 
```{r visualization}
map_1 <- all_df1 %>% filter(ID %in% c(1, 2, 3, 4, 5, 6))
map_2 <- all_df1 %>% filter(ID %in% c(6, 8, 9, 10, 11))
map_3 <- all_df1 %>% filter(ID %in% c(12, 14, 15, 16, 17))
map_4 <- all_df1 %>% filter(ID %in% c(18, 19, 20, 22, 23))
map_5 <- all_df1 %>% filter(ID %in% c(24, 25, 26, 28, 30))
map_6 <- all_df1 %>% filter(ID %in% c(31, 32, 33, 34, 35))
map_7 <- all_df1 %>% filter(ID %in% c(36, 37, 38, 40, 41))
map_8 <- all_df1 %>% filter(ID %in% c(44, 45, 46, 47, 48))

# map 1
whole_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
whole_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
whole_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
whole_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 5
whole_vis_5 <- ggplot(map_5, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 6
whole_vis_6 <- ggplot(map_6, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 7
whole_vis_7 <- ggplot(map_7, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 8
whole_vis_8 <- ggplot(map_8, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_grid(new_ID~group)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

save the plots as a pdf
```{r pdf whole example, echo=FALSE, results='hide'}
pdf("whole_hmm_sequence_map.pdf")
whole_vis_1
whole_vis_2
whole_vis_3
whole_vis_4
whole_vis_5
whole_vis_6
whole_vis_7
whole_vis_8
dev.off()
```

visualize with free scale 
```{r free vis}
# map 1
free_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
free_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
free_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
free_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 5
free_vis_5 <- ggplot(map_5, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 6
free_vis_6 <- ggplot(map_6, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 7
free_vis_7 <- ggplot(map_7, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 8
free_vis_8 <- ggplot(map_8, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

```{r pdf free example, echo=FALSE, results='hide'}
pdf("free_hmm_sequence_map.pdf")
free_vis_1
free_vis_2
free_vis_3
free_vis_4
free_vis_5
free_vis_6
free_vis_7
free_vis_8
dev.off()
```

# sequence over time 

visualization to HMM state sequence over time 
```{r state time visualization}
all_df2 <- all_df1 %>% 
  group_by(ID) %>% 
                   mutate(julian = yday(time),
                            week = lubridate::week(time)) %>% ungroup()# create the week column
#hmm_df$states <- as.factor(states) # factorize the state
#hmm_df$ID <- as.numeric(hmm_df$ID) # convert the ID to numeric
#hmm_df <- hmm_df %>% arrange(desc(ID)) # rearrange the ID by desc order

all_df2 <- all_df2 %>% dplyr::filter(group == "pool") %>% filter(status %in% c("u", "i"))

# visualize the trends 
fig4 <- ggplot(all_df2, aes(x = julian, y = ID))+
       geom_point(stat='identity', aes(col=state), size = 2)+
       #geom_line(stat = 'identity', aes(col=state), size = 1)+
       scale_y_discrete("ID", 
                        labels = as.character(all_df2$ID), 
                        breaks = all_df2$ID#, 
                        #expand = expansion(mult = c(0, .02),add = c(1, 0))
                        )+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
       theme_bw()+
  xlab("Time")

fig4
```

save the plot 
```{r save the plot}
pdf("figure4.pdf")
fig4
dev.off()
```

# Footer
```{r footer}
sessionInfo()
```