---
title: "6a.appendix"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)

# call environmental data
library(terra)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/hmm_sequence_data", "pool_hmm_shrub_sequence_final.rds"))

# only select the columns that we will use 
whole_df <- whole_df %>% dplyr::select("ID", "states", "x", "y")

# change the col name to "state"
names(whole_df)[2] <- "state"

whole_df
```

list of infection stats per id
```{r list of status}
n_oryx <- read_rds(here::here("data/ssf_data", "n_ssf_oryx.rds"))
u_oryx <- read_rds(here::here("data/ssf_data", "u_ssf_oryx.rds"))
i_oryx <- read_rds(here::here("data/ssf_data", "i_ssf_oryx.rds"))

n_list <- unique(n_oryx$ID)
u_list <- unique(u_oryx$ID)
i_list <- unique(i_oryx$ID)

rm(n_oryx, u_oryx, i_oryx)

# create a new ID
whole_df1 <- whole_df %>% mutate(status = ifelse(whole_df$ID %in% i_list, "i", ifelse(whole_df$ID %in% n_list, "n", "u")))

whole_df1$new_ID <- paste(whole_df1$status, whole_df1$ID, sep = "_")
whole_df1 %>% distinct(ID)
```

visualize 
```{r visualization}
map_1 <- whole_df1 %>% filter(ID %in% c(1, 2, 3, 4, 5, 6, 8, 9, 10, 11))
map_2 <- whole_df1 %>% filter(ID %in% c(12, 14, 15, 16, 17, 18, 19, 20, 22, 23))
map_3 <- whole_df1 %>% filter(ID %in% c(24, 25, 27, 28, 30, 31, 32, 33, 34, 35))
map_4 <- whole_df1 %>% filter(ID %in% c(36, 37, 38, 40, 41, 44, 45, 46, 47, 48))

# map 1
whole_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~new_ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
whole_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~new_ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
whole_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~new_ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
whole_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = new_ID))+
  #geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  coord_equal()+
  facet_wrap(~new_ID)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

save the plots as a pdf
```{r pdf whole example, echo=FALSE, results='hide'}
pdf("appendixA.pdf")
whole_vis_1
whole_vis_2
whole_vis_3
whole_vis_4
dev.off()
```

visualize with free scale 
```{r free vis}
# map 1
free_vis_1 <- ggplot(map_1, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~new_ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 2
free_vis_2 <- ggplot(map_2, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~new_ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 3
free_vis_3 <- ggplot(map_3, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~new_ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))

# map 4
free_vis_4 <- ggplot(map_4, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.05, position=position_jitter(h=0.1, w=0.1))+
  #geom_path(size = 0.4)+
  scale_color_manual(values = c("#fbb4ae", "#377eb8", "#4daf4a", "#984ea3", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_wrap(~new_ID, scales="free")+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))
```

```{r pdf free example, echo=FALSE, results='hide'}
pdf("appendixB.pdf")
free_vis_1
free_vis_2
free_vis_3
free_vis_4
dev.off()
```

# Footer
```{r footer}
sessionInfo()
```