---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)

# visualization 
library(ggplot2)
library(patchwork)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/hmm_visualization_data", "pool_hmm_sequence.rds"))
ind_df <- readr::read_rds(here::here("data/hmm_visualization_data", "npool_hmm_sequence.rds"))
#ran_df <- readr::read_rds(here::here("data/hmm_visualization_data", "whole_hmmTMB_sequence.rds"))

# only select the columns that we will use 
whole_df <- whole_df %>% dplyr::select("ID", "states", "x", "y", "time")
ind_df <- ind_df %>% dplyr::select("ID", "states", "x", "y", "time")

# change the col name to "state"
names(whole_df)[2] <- "state"
names(ind_df)[2] <- "state"

# create group names 
whole_df$group <- "pool"
ind_df$group <- "non_pool"
#ran_df$group <- "hmmTMB"

# bind two data 
all_df <- rbind(whole_df, ind_df)

# relevel the group 
all_df$group <- factor(all_df$group, level = c("pool", "non_pool"))

all_df
```

list of infection stats per id
```{r list of status}
n_oryx <- read_rds(here::here("data/ssf_data", "n_ssf_oryx.rds"))
u_oryx <- read_rds(here::here("data/ssf_data", "u_ssf_oryx.rds"))
i_oryx <- read_rds(here::here("data/ssf_data", "i_ssf_oryx.rds"))

n_list <- unique(n_oryx$ID)
u_list <- unique(u_oryx$ID)
i_list <- unique(i_oryx$ID)

rm(n_oryx, u_oryx, i_oryx)

# create a new ID
all_df1 <- all_df %>% mutate(status = ifelse(all_df$ID %in% i_list, "i", ifelse(all_df$ID %in% n_list, "n", "u")))

all_df1$new_ID <- paste(all_df1$status, all_df1$ID, sep = "_")
all_df1
```

visualize 
```{r visualization}
fig <- all_df1 %>% filter(ID %in% c(11, 20, 22, 37))

# new facet label names for dose variable 
id.labs <- c("i_11" = "Infected 11", 
               "i_22" =  "Infected 22", 
               "u_20" =  "Uknown 20", 
               "u_37" =  "Uknown 37")

# new facet label names for supp variable 
model.labs <- c("pool" = "Complete pool", 
               "non_pool" = "No pool")

# same scale 
fig3a <- ggplot(fig, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.7, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.4)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  #coord_equal()+
  facet_grid(new_ID~group,
             labeller = labeller(new_ID = id.labs, group = model.labs))+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45),
        legend.position = "none"
        )+
  xlab("Longtidue")+
  ylab("Latitude")#+
  #ggtitle("(a)")

# free scale 
fig3b <- ggplot(fig, mapping = aes(x, y, col = state, group = new_ID))+
  geom_point(size = 0.5, position=position_jitter(h=0.1, w=0.1))+
  geom_path(size = 0.01)+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  facet_wrap(new_ID~group,
             labeller = labeller(new_ID = id.labs, group = model.labs),
             scales = "free",
             ncol = 2)+
  theme(panel.border = element_rect(color = "grey", fill = NA, size = 1), 
        panel.background = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 5),
        axis.text.x = element_text(angle=45))+
  xlab("Longtidue")+
  ylab("Latitude")#+
  #ggtitle("(b)")

fig3a
fig3b
```

combine the plots 
```{r combine the plots}
# combine the figures 
#grid <- cowplot::plot_grid(fig3a, fig3b, nrow = 1, rel_widths = c(1/3,2/3), align = "h")

fig3a | fig3b + plot_annotation(tag_levels = "a")
```

save the plot 
```{r save the plot}
pdf("figure3.pdf")
fig3a
fig3b
dev.off()
```

# sequence over time 

visualization to HMM state sequence over time 
```{r state time visualization}
all_df1

all_df2 <- all_df1 %>% mutate(julian = yday(time),
                            week = lubridate::week(time)) # create the week column
#hmm_df$states <- as.factor(states) # factorize the state
#hmm_df$ID <- as.numeric(hmm_df$ID) # convert the ID to numeric
#all_df3 <- all_df3 %>% arrange(desc(ID)) # rearrange the ID by desc order

all_df3 <- all_df2 %>% dplyr::filter(status %in% c("i", "u"))

# relevel the factor
all_df3$ID <- factor(all_df3$ID, 
                     levels = c("2", "3", "4", "5", "6", "8", "9", "10", "11", "14", "15", "16", "17", "18", "19", "20", "22", "23", "24", "25", "27", "30", "33", "34", "36", "37", "40", "44", "45"))

# visualize the trends 
fig4 <- ggplot(all_df3, aes(x =julian, y = ID))+
       geom_point(stat='identity', aes(color=state, shape = state), size = 1.5)+
       #geom_line(stat = 'identity', aes(col=state), size = 1)+
       scale_y_discrete("ID", 
                        labels = as.character(all_df3$ID), 
                        breaks = all_df3$ID#, 
                        #expand = expansion(mult = c(0, .02),add = c(1, 0))
                        )+
  scale_color_manual(values = c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "black"),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  scale_shape_manual(values = c(16, 16, 17, 17, 15),
                     labels = c("NE", "NR", "IE", "IR", "D"))+
  facet_wrap(~group)+
       theme_bw()+
  xlab("Time")

fig4
```

save the plot 
```{r save the plot}
pdf("figure4.pdf")
fig4
dev.off()
```

# Footer
```{r footer}
sessionInfo()
```