---
title: "6.simulate_HMM"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# model output
m2 <- readr::read_rds(here::here("data/HMM_outputs", "hmm_m4_output.rds"))
```

prepare data for HMM format
```{r HMM formats}
# simulation model 
# 1. Pass a fitted model to simulate from
# (m is a momentuHMM object - as returned by fitHMM - automatically loaded with the package)
# We keep the default nbAnimals=1.

obsPerAnimal=c(500,700)

data <- momentuHMM::simData(model=m2, nbAnimals = 30, nbStates = 5, obsPerAnimal=obsPerAnimal, states = TRUE)

data

# save the sim_df
#saveRDS(data, here::here("data/simulation_data", "sim4_df.rds"))
```
prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data <- momentuHMM::prepData(data, type = "UTM", covNames = c("shrub", "states"))

# check the hmm dataset
head(data, 10)

# non-infected exploring: mean of non infected step and turn angle
data %>% filter(states == 1) %>% drop_na(.) %>% summarise(., step_mean = mean(step))
data %>% filter(states == 1) %>% drop_na(.) %>% summarise(., ta_mean = mean(angle))

# non-infected resting: mean of infected step and turn angle
data %>% filter(states == 2)  %>% drop_na(.) %>% summarise(., step_mean = mean(step))
data %>% filter(states == 2) %>% drop_na(.) %>% summarise(., ta_mean = mean(angle))

# infected exploring: mean of non infected step and turn angle
data %>% filter(states == 3)  %>% drop_na(.) %>% summarise(., step_mean = mean(step))
data %>% filter(states == 3) %>% drop_na(.) %>% summarise(., ta_mean = mean(angle))

# infected resting: mean of infected step and turn angle
data %>% filter(states == 4)  %>% drop_na(.)%>% summarise(., step_mean = mean(step))
data %>% filter(states == 4) %>% drop_na(.) %>% summarise(., ta_mean = mean(angle))

# death: mean of death step and turn angle
data %>% filter(states == 5) %>% drop_na(.) %>% summarise(., step_mean = mean(step))
data %>% filter(states == 5) %>% drop_na(.) %>% summarise(., ta_mean = mean(angle))
```

# model fitting - a 5-state HMM

```{r 5 state hmm covariates}
# number of states 
nbStates <- 5

# label states
stateNames <- c("1" = "NE","2" = "NR","3" = "IE","4" = "IR","5" = "D")

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# Initial parameters
# (step mean for state 1, step mean for state 2, step mean for state N so on... same for step SD s1, step SD s2) and (angle concentration s1, angle concentration s2)
Par0_5s <- list(       # mean
                step = c(400, 50, 250, 50, 4,
                       # sd
                         400, 50, 250, 50, 4), 
                angle = c(0.05, 0.1, 0.01, 0.1, 0.001)
                )

# constrain transition probabilities - fix the transition probability matrix to prevent some of the transitions 
#we set to NA the columns of unconstrained transition probabilities, and we again fix the intercept of the other columns to a large negative number (here -1e6) to set the corresponding transition probabilities to be virtually zero (i.e., impossible transition).
fixbeta <-  matrix(c( # NE: 1->2          1->3            1->4          1->5
                            NA, NA,       -1e6, -1e6,     -1e6, -1e6,   -1e6, -1e6,
                      # NR: 2->1          2->3            2->4          2->5
                            NA, NA,       -1e6, -1e6,     NA, NA,       NA, NA,
                      # IE: 3->1          3->2            3->4          3->5
                            -1e6, -1e6,   -1e6, -1e6,     NA, NA,       -1e6, -1e6,
                      # IR: 4->1          4->2            4->3          4->5  
                            -1e6, -1e6,   -1e6, -1e6,     NA, NA,       NA, NA,
                      # D: 5->1           5->2            5->3          5->4
                            -1e6, -1e6,   -1e6, -1e6,     -1e6, -1e6,   -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)

# Fit a 5-state HMM
hmm <- momentuHMM::fitHMM(data, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_5s,
                          formula = ~shrub,
                          fixPar = fixPar,
                          stateNames = stateNames)
```

model visualization - hmm
```{r hmm model output}
# Print parameter estimates
hmm

# save the hmm output 
saveRDS(hmm, here::here("data/HMM_outputs", "hmm_sim4_output.rds"))
```

```{r hmm visualization}
# Plot estimated distributions and state-coloured tracks
plot(hmm, breaks = 20, ask = FALSE)
```

save the plots as a pdf
```{r example, echo=FALSE, results='hide'}
pdf("HMM_sim4.pdf")
plot(hmm, breaks = 20, ask=FALSE)
dev.off()
```

take out the estimates from the fitted model HMM 
```{r model outputs}
# bring out the reconstructed most probable states sequence 
states <- momentuHMM::viterbi(hmm)

# add states into hmm
data$est_state <- states
data

# save the rds file for the state sequences 
saveRDS(data, here::here("data/hmm_sequence_data", "HMM_sim4_sequence.rds"))
```

# Footer
```{r footer}
sessionInfo()
```
