---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/HMM", "HMM_prep_data.Rdata"))
n_oryx <- read_rds(here::here("data/ssf_data", "n_ssf_oryx.rds"))
u_oryx <- read_rds(here::here("data/ssf_data", "u_ssf_oryx.rds"))
i_oryx <- read_rds(here::here("data/ssf_data", "i_ssf_oryx.rds"))

# convert the shrub cover values to percentage 
whole_df <- whole_df %>% mutate(per_shrub = (shrub/100))

# create bern body condition index - if optimal or over = 0, else under = 1
#whole_df <- whole_df %>% mutate(BC = ifelse(c_avg_BC == "under", 1, 0))

# non-infecetd list 
n_list <- unique(n_oryx$ID)

# unknown and infected list 
u_i_oryx <- rbind(u_oryx, i_oryx)
u_i_list <- unique(u_i_oryx$ID)

# filter by unknown and infected list 
u_i_prep <- whole_df %>% filter(ID %in% u_i_list)
n_prep <- whole_df %>% filter(ID %in% n_list)

rm(u_i_oryx, u_i_list, n_list,  whole_df) # remove the unnecessary dataset

# make sure each individual start with the state from 0 
u_i_prep <- u_i_prep %>% 
  group_by(ID) %>% # grouping by ID
  mutate(row_number = row_number()) %>% # adding a row number for each group 
  mutate(infection = ifelse(row_number <= 24, 0, infection)) %>% # assigning value 0 to the first 10 rows per group
  dplyr::select(- c(row_number, shrub, c_avg_BC)) %>% # un-select the row_number column
  ungroup(ID)

u_i_prep <- data.frame(u_i_prep) # convert it to the dataframe

# set infection status for the non-infected as 0 
n_prep <- n_prep %>% mutate(infection = 0) %>% dplyr::select(- c(shrub, c_avg_BC))
n_prep

# bind two data into hmm prep_dat
hmm_prep_dat <- rbind(n_prep, u_i_prep)

# remove unnecessary dataset 
rm(u_i_prep, n_prep)
```

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(hmm_prep_dat, type = "UTM")

# check the hmm dataset
head(data_hmm, 10)
```

get the mean step and ta per group 
```{r movement params inf}
n_list <- n_oryx %>% distinct(ID) %>% arrange(ID)
u_list <- u_oryx %>% distinct(ID) %>% arrange(ID)
i_list <- i_oryx %>% distinct(ID) %>% arrange(ID)

# non-infected
data_hmm %>% 
  filter(ID %in% n_list$ID) %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# unknown 
data_hmm %>% 
  filter(ID %in% u_list$ID) %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# infected
data_hmm %>% 
  filter(ID %in% i_list$ID) %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
```

# initital parameters per group
```{r init params inf}
# Initial parameters
# (step mean for state 1, step mean for state 2, step mean for state N so on... same for step SD s1, step SD s2) and (angle concentration s1, angle concentration s2)

# non-infected
Par0_4s_n <- list(step = c(465, 25, 250, 25,
                           465, 25, 250, 25), 
                angle = c(0.008, 0.1, 0.02, 0.1))

# unknown
Par0_4s_u <- list(step = c(370, 50, 200, 50,
                           370, 50, 200, 50), 
                angle = c(0.06, 0.1, 0.03, 0.1))

# infected
Par0_4s_i <- list(step = c(295, 50, 150, 50,
                           295, 50, 150, 50), 
                angle = c(0.03, 0.3, 0.01, 0.3))
```

# model set up
```{r model set up}
# number of states 
nbStates <- 4

# label states
stateNames <- c('1' = 'NE', '2' = 'NR', '3' = 'IE', '4' = 'IR')

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# constrain transition probabilities - fix the transition probability matrix to prevent some of the transitions - we set to NA the columns of unconstrained transition probabilities, and we again fix the intercept of the other columns to a large negative number (here -1e6) to set the corresponding transition probabilities to be virtually zero (i.e., impossible transition).
fixbeta <-  matrix(c(NA, -1e6, -1e6,
                     NA, -1e6, NA,
                     -1e6, -1e6, NA,
                     -1e6, -1e6, NA), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)
```

# model fit
```{r hmm ni}
# subset the data 
# subset the data 
hmm_n <- data_hmm %>% filter(ID %in% n_list$ID)

# empty list for storing each model fit 
hmm_n_list <- list()

for (id in unique(hmm_n$ID)) {
  id_data <- hmm_n %>% filter(ID == id)
  
  hmm_n_list[[id]] <- momentuHMM::fitHMM(id_data,
                                         nbStates = nbStates,
                                         fixPar = fixPar,
                                         dist = dist,
                                         Par0 = Par0_4s_n,
                                         stateNmeas = stateNames)
}

#hmm_n_list

# save the hmm output 
#saveRDS(hmm_n_list, "individual_n_hmm.rds")
```

```{r hmm unk}
# subset the data 
hmm_u <- data_hmm %>% filter(ID %in% u_list$ID)

# empty list for storing each model fit 
hmm_u_list <- list()

for (id in unique(hmm_u$ID)) {
  id_data <- hmm_u %>% filter(ID == id)
  
  hmm_u_list[[id]] <- momentuHMM::fitHMM(id_data,
                                         nbStates = nbStates,
                                         fixPar = fixPar,
                                         dist = dist,
                                         Par0 = Par0_4s_u,
                                         stateNmeas = stateNames)
}

#hmm_u_list

# save the hmm output 
saveRDS(hmm_u_list, "individual_u_hmm.rds")
```

```{r hmm inf}
# subset the data 
hmm_i <- data_hmm %>% filter(ID %in% i_list$ID)

# empty list for storing each model fit 
hmm_i_list <- list()

for (id in unique(hmm_i$ID)) {
  id_data <- hmm_i %>% filter(ID == id)
  
  hmm_i_list[[id]] <- momentuHMM::fitHMM(id_data,
                                         nbStates = nbStates,
                                         fixPar = fixPar,
                                         dist = dist,
                                         Par0 = Par0_4s_i,
                                         stateNmeas = stateNames)
}

#hmm_i_list

# save the hmm output 
saveRDS(hmm_i_list, "individual_i_hmm.rds")
```

get all the state switching info per ind model fit

```{r ninf state switching model fits}
# get the empty list for storing each id states
states_id <- list()

for (i in 1:length(hmm_n_list)) {
  # call each hmm model fit from list per id
  hmm_output <- hmm_n_list[[i]]
  
  # store state swtiching info per each model fit 
  states_id[[i]] <- momentuHMM::viterbi(hmm_output)
}

state_n_dat <- unlist(states_id)

hmm_n$states <- factor(state_n_dat, levels = c("1", "2", "3", "4"))

# save the rds file for the state sequences 
#saveRDS(hmm_n, "ninfected_hmm_sequence.rds")
```

```{r unkn state switching model fits}
# get the empty list for storing each id states
states_id <- list()

for (i in 1:length(hmm_u_list)) {
  # call each hmm model fit from list per id
  hmm_output <- hmm_u_list[[i]]
  
  # store state swtiching info per each model fit 
  states_id[[i]] <- momentuHMM::viterbi(hmm_output)
}

state_u_dat <- unlist(states_id)

hmm_u$states <- factor(state_u_dat, levels = c("1", "2", "3", "4"))

# save the rds file for the state sequences 
#saveRDS(hmm_u, "unknown_hmm_sequence.rds")
```


```{r inf state switching model fits}
# get the empty list for storing each id states
states_id <- list()

for (i in 1:length(hmm_i_list)) {
  # call each hmm model fit from list per id
  hmm_output <- hmm_i_list[[i]]
  
  # store state swtiching info per each model fit 
  states_id[[i]] <- momentuHMM::viterbi(hmm_output)
}

state_i_dat <- unlist(states_id)

hmm_i$states <- factor(state_i_dat, levels = c("1", "2", "3", "4"))

# save the rds file for the state sequences 
#saveRDS(hmm_i, "infected_hmm_sequence.rds")
```

combine the whole data together
```{r hmm visualization}
hmm_individual_df <- rbind(hmm_n, hmm_u, hmm_i)

hmm_individual_df

#save the rds file for the state sequences 
#saveRDS(hmm_individual_df, "individual_whole_hmm_sequence.rds")
```

visualize the state sequence over spatial 
```{r state spatial visualization}
map_1 <- hmm_individual_df %>% filter(ID %in% c(1, 2, 3, 4, 5, 6))

map_1

ggplot(map_1, aes(x = x, y = y))+
  geom_path(size = 0.7, aes(color = states))+
  scale_color_manual(values = c("#238b45", "#88419d", "#d7301f", "#0570b0"),
                     labels = c("NE", "NR", "IE", "IR"))+
  coord_equal()+
  facet_wrap(~ID, ncol = 1)
```

# Footer
```{r footer}
sessionInfo()
```