---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/HMM", "40inds_final_hmm_prep_data.rds"))

# only select infected ones 
u_oryx <- read_rds(here::here("data/ssf_data", "u_ssf_oryx.rds"))

u_list <- u_oryx %>% distinct(ID) %>% arrange(ID)

unk_df <- whole_df %>% filter(ID %in% u_list$ID)

rm(whole_df)

unk_df %>% distinct(ID) # 2, 3, 4, 5, 6, 8, 9, 10, 14, 15, 16, 17, 19, 20, 23, 24, 25, 27, 30, 33, 34, 37, 40, 44, 45
```

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(unk_df, type = "UTM")

# check the hmm dataset
head(data_hmm, 10)
```

get the mean step and ta per group 
```{r movement params unk}
# 2, 3, 4, 5, 6, 8, 9, 10, 14, 15, 16, 17, 19, 20, 23, 24, 25, 27, 30, 33, 34, 37, 40, 44, 45

# 2
data_hmm %>% 
  filter(ID == "2") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 3 
data_hmm %>% 
  filter(ID == "3") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 4
data_hmm %>% 
  filter(ID == "4") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 5
data_hmm %>% 
  filter(ID == "5") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 6
data_hmm %>% 
  filter(ID == "6") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 8 
data_hmm %>% 
  filter(ID == "8") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 9
data_hmm %>% 
  filter(ID == "9") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 10
data_hmm %>% 
  filter(ID == "10") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 14
data_hmm %>% 
  filter(ID == "14") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 15 
data_hmm %>% 
  filter(ID == "15") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 16
data_hmm %>% 
  filter(ID == "16") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 17
data_hmm %>% 
  filter(ID == "17") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 19
data_hmm %>% 
  filter(ID == "19") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 20
data_hmm %>% 
  filter(ID == "20") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 23
data_hmm %>% 
  filter(ID == "23") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 24
data_hmm %>% 
  filter(ID == "24") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 25 
data_hmm %>% 
  filter(ID == "25") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 27
data_hmm %>% 
  filter(ID == "27") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 30
data_hmm %>% 
  filter(ID == "30") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 33
data_hmm %>% 
  filter(ID == "33") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 34 
data_hmm %>% 
  filter(ID == "34") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 37
data_hmm %>% 
  filter(ID == "37") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 40
data_hmm %>% 
  filter(ID == "40") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))

# 44
data_hmm %>% 
  filter(ID == "44") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 45
data_hmm %>% 
  filter(ID == "45") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
```

# initital parameters per group
```{r init params unk}
# 2, 3, 4, 5, 6, 8, 9, 10, 14, 15, 16, 17, 19, 20, 23, 24, 25, 27, 30, 33, 34, 37, 40, 44, 45

# Initial parameters
Par0_5s_list <- list()
# 2
Par0_5s_list[[1]] <- list(step = c(157, 40, 75, 40, 1,
                                   157, 40, 75, 40, 1), 
                          angle = c(0.08, 0.1, 0.02, 0.1, 0.001))
# 3
Par0_5s_list[[2]] <- list(step = c(227, 50, 100, 50, 1,
                                   227, 50, 100, 50, 1), 
                          angle = c(0.04, 0.1, 0.03, 0.1, 0.001))
# 4
Par0_5s_list[[3]] <- list(step = c(540, 75, 300, 75, 1,
                                   540, 75, 300, 75, 1), 
                          angle = c(0.015, 0.1, 0.01, 0.1, 0.001))
# 5
Par0_5s_list[[4]] <- list(step = c(300, 50, 150, 50, 1,
                                   300, 50, 150, 50, 1), 
                          angle = c(0.11, 0.3, 0.03, 0.3, 0.001))
# 6
Par0_5s_list[[5]] <- list(step = c(725, 100, 400, 100, 1,
                                   725, 100, 400, 100, 1), 
                          angle = c(0.007, 0.3, 0.003, 0.3, 0.001))
# 8
Par0_5s_list[[6]] <- list(step = c(846, 100, 400, 100, 1,
                                   846, 100, 400, 100, 1), 
                          angle = c(0.06, 0.1, 0.02, 0.1, 0.001))
# 9
Par0_5s_list[[7]] <- list(step = c(144, 30, 70, 30, 1,
                                   144, 30, 70, 30, 1), 
                          angle = c(0.2, 0.1, 0.15, 0.1, 0.001))

# 10
Par0_5s_list[[8]] <- list(step = c(1528, 150, 700, 150, 1,
                                   1528, 150, 700, 150, 1),
                          angle = c(0.004, 0.1, 0.01, 0.1, 0.001))
# 14
Par0_5s_list[[9]] <- list(step = c(250, 50, 100, 50, 1,
                                   250, 50, 100, 50, 1), 
                          angle = c(0.28, 0.3, 0.1, 0.3, 0.001))
# 15
Par0_5s_list[[10]] <- list(step = c(326, 50, 150, 50, 1,
                                    326, 50, 150, 50, 1),
                           angle = c(0.09, 0.3, 0.03, 0.3, 0.001))
# 16
Par0_5s_list[[11]] <- list(step = c(465, 50, 200, 50, 1,
                                    465, 50, 200, 50, 1), 
                           angle = c(0.07, 0.1, 0.02, 0.1, 0.001))
# 17
Par0_5s_list[[12]] <- list(step = c(460, 50, 200, 50, 1,
                                    460, 50, 200, 50, 1), 
                           angle = c(0.07, 0.1, 0.02, 0.1, 0.001))
# 19
Par0_5s_list[[13]] <- list(step = c(764, 50, 350, 50, 1,
                                    764, 50, 350, 50, 1),
                           angle = c(0.11, 0.1, 0.05, 0.1, 0.001))
# 20
Par0_5s_list[[14]] <- list(step = c(258, 50, 100, 50, 1,
                                    258, 50, 100, 50, 1),
                           angle = c(0.01, 0.3, 0.03, 0.3, 0.001))
# 23
Par0_5s_list[[15]] <- list(step = c(1172, 150, 600, 150, 1,
                                    1172, 150, 600, 150, 1), 
                           angle = c(0.08, 0.3, 0.03, 0.3, 0.001))
# 24
Par0_5s_list[[16]] <- list(step = c(376, 50, 150, 50, 1,
                                    376, 50, 150, 50, 1), 
                           angle = c(0.01, 0.1, 0.02, 0.1, 0.001))
# 25
Par0_5s_list[[17]] <- list(step = c(1493, 250, 700, 250, 1,
                                    1493, 250, 700, 250, 1),
                           angle = c(0.02, 0.1, 0.03, 0.1, 0.001))
# 27
Par0_5s_list[[18]] <- list(step = c(306, 50, 100, 50, 1,
                                    306, 50, 100, 50, 1), 
                           angle = c(0.07, 0.3, 0.03, 0.3, 0.001))
# 30
Par0_5s_list[[19]] <- list(step = c(500, 50, 250, 50, 1,
                                    500, 50, 250, 50, 1), 
                           angle = c(0.16, 0.3, 0.1, 0.3, 0.001))
# 33
Par0_5s_list[[20]] <- list(step = c(1119, 250, 500, 250, 1,
                                    1119, 250, 500, 250, 1),
                           angle = c(0.11, 0.3, 0.2, 0.3, 0.001))
# 34
Par0_5s_list[[21]] <- list(step = c(356, 50, 150, 50, 1,
                                    356, 50, 150, 50, 1),
                           angle = c(0.03, 0.1, 0.05, 0.1, 0.001))
# 37
Par0_5s_list[[22]] <- list(step = c(407, 50, 200, 50, 1,
                                    407, 50, 200, 50, 1),
                           angle = c(0.02, 0.1, 0.01, 0.1, 0.001))
# 40
Par0_5s_list[[23]] <- list(step = c(606, 100, 300, 100, 1,
                                    606, 10, 300, 100, 1), 
                           angle = c(0.08, 0.1, 0.01, 0.1, 0.001))
# 44
Par0_5s_list[[24]] <- list(step = c(286, 50, 100, 50, 1,
                                    286, 50, 100, 50, 1),
                           angle = c(0.06, 0.3, 0.03, 0.3, 0.001))
# 45
Par0_5s_list[[25]] <- list(step = c(190, 30, 90, 30, 1,
                                    190, 30, 90, 30, 1), 
                           angle = c(0.35, 0.3, 0.2, 0.3, 0.001))
```

# model set up
```{r model set up}
# number of states 
nbStates <- 5

# label states
stateNames <- c('1' = 'NE', '2' = 'NR', '3' = 'IE', '4' = 'IR', '5' = 'D')

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# constrain transition probabilities - fix the transition probability matrix to prevent some of the transitions - we set to NA the columns of unconstrained transition probabilities, and we again fix the intercept of the other columns to a large negative number (here -1e6) to set the corresponding transition probabilities to be virtually zero (i.e., impossible transition).
#1->2 1->3 1->4 1->5
#2->1 2->3 2->4 2->5
#3->1 3->2 3->4 3->5
#4->1 4->2 4->3 4->5
#5->1 5->2 5->3 5->4

fixbeta <-  matrix(c(NA, -1e6, -1e6, -1e6,
                     NA, -1e6, NA, -1e6,
                     -1e6, -1e6, NA, NA,
                     -1e6, -1e6, NA, NA,
                     -1e6, -1e6, -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)
```

# model fit
```{r hmm unk}
# subset the data 
hmm_u <- data_hmm %>% filter(ID %in% u_list$ID)

# empty list for storing each model fit 
hmm_u_list <- list()

for (id in unique(hmm_u$ID)) {
  id_data <- hmm_u %>% filter(ID == id)
  
  for(j in length(unique(hmm_u$ID))){
  
  hmm_u_list[[id]] <- momentuHMM::fitHMM(id_data,
                                         nbStates = nbStates,
                                         fixPar = fixPar,
                                         dist = dist,
                                         Par0 = Par0_5s_list[[j]],
                                         stateNames = stateNames)
  }
}

#hmm_u_list

# save the hmm output 
saveRDS(hmm_u_list, "npool_u_hmm.rds")
```


get all the state switching info per ind model fit

```{r unkn state switching model fits}
# get the empty list for storing each id states
states_id <- list()

for (i in 1:length(hmm_u_list)) {
  # call each hmm model fit from list per id
  hmm_output <- hmm_u_list[[i]]
  
  # store state swtiching info per each model fit 
  states_id[[i]] <- momentuHMM::viterbi(hmm_output)
}

state_u_dat <- unlist(states_id)

hmm_u$states <- factor(state_u_dat, levels = c("1", "2", "3", "4", "5"))

# save the rds file for the state sequences 
saveRDS(hmm_u, "npool_u_hmm_sequence.rds")
```

# Footer
```{r footer}
sessionInfo()
```