---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

Read in the prep data
```{r read in prep data}
# Location data of the oryx 
whole_df <- readr::read_rds(here::here("data/HMM", "40inds_final_hmm_prep_data.rds"))

# only select infected ones 
i_oryx <- read_rds(here::here("data/ssf_data", "i_ssf_oryx.rds"))

i_list <- i_oryx %>% distinct(ID) %>% arrange(ID)

inf_df <- whole_df %>% filter(ID %in% i_list$ID)

rm(whole_df)

inf_df %>% distinct(ID) # 11, 18, 22, 36
```

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(inf_df, type = "UTM")

# check the hmm dataset
head(data_hmm, 10)
```

get the mean step and ta per group 
```{r movement params inf}
# 11
data_hmm %>% 
  filter(ID == "11") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 18 
data_hmm %>% 
  filter(ID == "18") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 22
data_hmm %>% 
  filter(ID == "22") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
# 36
data_hmm %>% 
  filter(ID == "36") %>% 
  group_by(infection) %>% 
  dplyr::summarize(step_mean = mean(step, na.rm = TRUE),
                   ta_mean = mean(angle, na.rm = TRUE))
```

# initital parameters per group
```{r init params inf}
# Initial parameters
Par0_5s_list <- list()
#11
Par0_5s_list[[1]] <- list(step = c(300, 50, 150, 50, 1,
                                   300, 50, 150, 50, 1), 
                          angle = c(0.05, 0.1, 0.01, 0.1, 0.001))

# 18
Par0_5s_list[[2]] <- list(step = c(400, 50, 250, 50, 1,
                                   400, 50, 250, 50, 1), 
                          angle = c(0.05, 0.1, 0.01, 0.1, 0.001))

# 22
Par0_5s_list[[3]] <- list(step = c(250, 50, 150, 50, 1,
                                   250, 50, 150, 50, 1), 
                          angle = c(0.05, 0.1, 0.01, 0.1, 0.001))

# 36
Par0_5s_list[[4]] <- list(step = c(235, 50, 130, 50, 1,
                                   235, 50, 130, 50, 1), 
                angle = c(0.05, 0.1, 0.01, 0.3, 0.001))
```

# model set up
```{r model set up}
# number of states 
nbStates <- 5

# label states
stateNames <- c('1' = 'NE', '2' = 'NR', '3' = 'IE', '4' = 'IR', '5' = 'D')

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# constrain transition probabilities - fix the transition probability matrix to prevent some of the transitions - we set to NA the columns of unconstrained transition probabilities, and we again fix the intercept of the other columns to a large negative number (here -1e6) to set the corresponding transition probabilities to be virtually zero (i.e., impossible transition).
#1->2 1->3 1->4 1->5
#2->1 2->3 2->4 2->5
#3->1 3->2 3->4 3->5
#4->1 4->2 4->3 4->5
#5->1 5->2 5->3 5->4

fixbeta <-  matrix(c(NA, -1e6, -1e6, -1e6,
                     NA, -1e6, NA, -1e6,
                     -1e6, -1e6, NA, NA,
                     -1e6, -1e6, NA, NA,
                     -1e6, -1e6, -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)
```

# model fit
```{r hmm inf}
# subset the data 
hmm_i <- data_hmm %>% filter(ID %in% i_list$ID)

# empty list for storing each model fit 
hmm_i_list <- list()

for (id in unique(hmm_i$ID)) {
  id_data <- hmm_i %>% filter(ID == id)
  
  for(j in length(unique(hmm_i$ID))){
  
  hmm_i_list[[id]] <- momentuHMM::fitHMM(id_data,
                                         nbStates = nbStates,
                                         fixPar = fixPar,
                                         dist = dist,
                                         Par0 = Par0_5s_list[[j]],
                                         stateNames = stateNames)
  }
}

#hmm_i_list

# save the hmm output 
saveRDS(hmm_i_list, "npool_i_hmm.rds")
```

get all the state switching info per ind model fit

```{r inf state switching model fits}
# get the empty list for storing each id states
states_id <- list()

for (i in 1:length(hmm_i_list)) {
  # call each hmm model fit from list per id
  hmm_output <- hmm_i_list[[i]]
  
  # store state swtiching info per each model fit 
  states_id[[i]] <- momentuHMM::viterbi(hmm_output)
}

state_i_dat <- unlist(states_id)

hmm_i$states <- factor(state_i_dat, levels = c("1", "2", "3", "4", "5"))

# save the rds file for the state sequences 
saveRDS(hmm_i, "npool_i_hmm_sequence.rds")
```

combine the whole data together
```{r hmm visualization}
hmm_i <- readr::read_rds(here::here("data/hmm_visualization_data", "npool_i_hmm_sequence.rds"))
hmm_u <- readr::read_rds(here::here("data/hmm_visualization_data", "npool_u_hmm_sequence.rds"))
hmm_n <- readr::read_rds(here::here("data/hmm_visualization_data", "npool_n_hmm_sequence.rds"))

hmm_individual_df <- rbind(hmm_n, hmm_u, hmm_i)

hmm_individual_df

#save the rds file for the state sequences 
saveRDS(hmm_individual_df, "npool_hmm_sequence.rds")
```

visualize the state sequence over spatial - check
```{r state spatial visualization}
map_1 <- hmm_individual_df %>% filter(ID %in% c(1, 2, 3, 4, 5, 6))

map_1

ggplot(map_1, aes(x = x, y = y))+
  geom_path(size = 0.7, aes(color = states))+
  scale_color_manual(values = c("#238b45", "#88419d", "#d7301f", "#0570b0"),
                     labels = c("NE", "NR", "IE", "IR"))+
  coord_equal()+
  facet_wrap(~ID, ncol = 1)
```

# Footer
```{r footer}
sessionInfo()
```