---
title: "6.fit_HMM_oryx"
author: "Dennis Kim"
date: "2024-01-22"
output: html_document
---

# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)
library(forcats)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)

# visualization 
library(ggplot2)
library(patchwork)

options(width = 150)
```

Read in the prep data
```{r read in prep data}
# estimated sequence
sim_sequence <- readr::read_rds(here::here("data/hmm_sequence_data", "HMM_simulation_sequence.rds"))

colnames(sim_sequence)[8] <- "null_state"
colnames(sim_sequence)[9] <- "est_state"

# compare the accuracy 
sim_sequence$accu <- ifelse(sim_sequence$null_state == sim_sequence$est_state, 1, 0)

sim_sequence

sim_sequence <- sim_sequence %>% dplyr::select(ID, time, null_state, est_state, accu)
```

# accuracy metrics 
```{r accuracy matrix}
# Step 1: Calculate accuracy metrics
accuracy <- mean(sim_sequence$accu)

precision <- sum(sim_sequence$accu[sim_sequence$est_state == sim_sequence$null_state]) / sum(sim_sequence$est_state == sim_sequence$null_state)

recall <- sum(sim_sequence$accu[sim_sequence$est_state == sim_sequence$null_state]) / sum(sim_sequence$null_state == sim_sequence$null_state)

f1_score <- 2 * (precision * recall) / (precision + recall)

# Step 2: Create confusion matrix
conf_matrix <- table(sim_sequence$null_state, sim_sequence$est_state)
conf_matrix
```


confusion matrix
```{r confusion matrix}
# Create a dataframe for the confusion matrix
conf_matrix <- table(sim_sequence$null_state, sim_sequence$est_state)

# Step 3: Visualize confusion matrix
conf_matrix_df <- as.data.frame.matrix(conf_matrix)
conf_matrix_df <- cbind(actual_state = rownames(conf_matrix_df), conf_matrix_df)
conf_matrix_df <- gather(conf_matrix_df, estimated_state, frequency, -actual_state)
conf_matrix_df

## change the factorized values names
conf_matrix_df <- conf_matrix_df %>%
  mutate(
    actual_state = case_when(
      actual_state == 1 ~ "NE",
      actual_state == 2 ~ "NR",
      actual_state == 3 ~ "IE",
      actual_state == 4 ~ "IR",
      actual_state == 5 ~ "D",
      TRUE ~ "Unknown"
    ),
    estimated_state = case_when(
      estimated_state == 1 ~ "NE",
      estimated_state == 2 ~ "NR",
      estimated_state == 3 ~ "IE",
      estimated_state == 4 ~ "IR",
      estimated_state == 5 ~ "D",
      TRUE ~ "Unknown"
    )
  )

## factorize the x and y axis columns 
conf_matrix_df$actual_state <- factor(conf_matrix_df$actual_state, levels = c("NE", "NR", "IE","IR", "D"))
conf_matrix_df$estimated_state <- factor(conf_matrix_df$estimated_state, levels = c("NE", "NR", "IE","IR", "D"))
```

```{r vis}
# Plot the confusion matrix
fig10 <- ggplot(data = conf_matrix_df, aes(y = reorder(actual_state, desc(actual_state)), x= estimated_state, fill = frequency)) +
  geom_tile(color = "black") +
  scale_fill_gradient2(
    low = "white", high = "#b30000",
    limit = c(0, 10000), space = "Lab",
    name = "Frequency"
    )+
    coord_fixed()+
  geom_text(aes(label = paste0(round(frequency, 1))), color = "black", size = 4)+
  scale_x_discrete(position = "top")+
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1), 
        panel.background = element_blank())+
  labs(x = "Estimated state", y = "Actual state", fill = "Frequency")

fig10
```

# Footer
```{r footer}
sessionInfo()
```
