# Document Preamble 
```{r preamble, message=FALSE, warning=FALSE}
# load libraries
library(knitr)
library(dplyr)
library(readr)
library(data.table)
library(here)
library(stringr)
library(tidyr)
library(purrr)
library(lubridate)
library(scales)

# call environmental data
library(terra)

# analysis
library(momentuHMM)
library(adehabitatLT)
library(mitools)

# visualization 
library(ggplot2)

options(width = 150)
```

## 1.1. Format of tracking data

prepare data for HMM format
```{r HMM formats}
# prepare data for HMM (compute step lengths and turning angles)
data_hmm <- momentuHMM::prepData(oryx.2018, type = "UTM", covNames = c("shrub", "time_since_release"))
```

# Non-constrained 4-state HMM

null model without any restriction
```{r 4 state hmm covariates}
# number of states 
nbStates <- 5

# label states
stateNames <- c("1" = "SE","2" = "SR","3" = "IE", "4" = "IR", "5" = "D")

# Observation distributions (step lengths, turning angles)
dist <- list(step = "gamma", 
             angle = "vm")

# Initial parameters
# (step mean for state 1, step mean for state 2, step mean for state N so on... same for step SD s1, step SD s2) and (angle concentration s1, angle concentration s2)
Par0_5s <- list(step = c(1800, 750, 220, 15, 2.5,   # step means
                         1050, 484, 220, 12, 1),  # step sds
                angle = c(-0.03, -0.009, 0.4, -3.1, pi,  # angle means
                          1.8, 0.53, 0.01, 0.3, 0.3) # angle concentrations
               )

# Specify whether to estimate angle means
estAngleMean <- list(angle = TRUE)

# only constraining the death so that it can be an observing state 
fixbeta0 <-  matrix(c( # NE: 1->2          1->3                1->4                1->5
                            NA, NA, NA,   NA, NA, NA,   NA, NA, NA,   NA, NA, NA,
                      # NR: 2->1          2->3                  2->4              2->5
                            NA, NA, NA,   NA, NA, NA,     NA, NA, NA,       NA, 0, 0,
                      # IE: 3->1                3->2                3->4          3->5
                            NA, NA, NA,   NA, NA, NA,   NA, NA, NA,   NA, NA, NA,
                      # IR: 4->1                4->2                4->3          4->5  
                            NA, NA, NA,   NA, NA, NA,   NA, NA, NA,  NA, NA, NA,
                      # D: 5->1           5->2            5->3          5->4
                            -1e6, -1e6, -1e6,  -1e6, -1e6,  -1e6,   -1e6, -1e6, -1e6,  -1e6, -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar0 <- list(beta = fixbeta0)

# Fit an unconstrained model
hmm <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_5s,
                          fixPar = fixPar0,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          #knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm
```

save the viberti 1
```{r state spatial visualization}
states <- momentuHMM::viterbi(hmm)
data_hmm1 <- data.frame(data_hmm)
data_hmm1$states <- states
data_hmm1$states <- factor(states, levels = c("1", "2", "3", "4", "5"))

data_hmm1
```

# Constrained 4-state HMM
```{r constrained 4states}
# make sure the transition between resting to death for shrub cover effects also 0 -- independent. 
fixbeta <-  matrix(c( # NE: 1->2          1->3                1->4                1->5
                            NA, NA, NA,   -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6,
                      # NR: 2->1          2->3                  2->4              2->5
                            NA, NA, NA,   -1e6, -1e6, -1e6,     NA, NA, NA,       NA, 0, 0,
                      # IE: 3->1                3->2                3->4          3->5
                            -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6,   NA, NA, NA,   -1e6, -1e6, -1e6,
                      # IR: 4->1                4->2                4->3          4->5  
                            -1e6, -1e6, -1e6,   -1e6, -1e6, -1e6,   NA, NA, NA,   NA, 0, 0,
                      # D: 5->1           5->2            5->3          5->4
                            -1e6, -1e6, -1e6,  -1e6, -1e6,  -1e6,   -1e6, -1e6, -1e6,  -1e6, -1e6, -1e6), 
                   nrow = 1, 
                   byrow = TRUE)

# fix initial values 
fixPar <- list(beta = fixbeta)

# Fit a constrained model
hmm2 <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_5s,
                          fixPar = fixPar,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          #knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm2
```

save the viberti 2
```{r state spatial visualization}
states <- momentuHMM::viterbi(hmm2)
data_hmm2 <- data.frame(data_hmm)
data_hmm2$states <- states
data_hmm2$states <- factor(states, levels = c("1", "2", "3", "4", "5"))

data_hmm2
```

# constrained model with known states
```{r cs known states}
# Fit a constrained model
hmm3 <- momentuHMM::fitHMM(data_hmm, 
                          nbStates = nbStates, 
                          dist = dist, 
                          Par0 = Par0_5s,
                          fixPar = fixPar,
                          formula = ~shrub + time_since_release,
                          estAngleMean = estAngleMean,
                          knownStates=data_hmm$death,
                          stateNames = stateNames)

hmm3
```

# Footer
```{r footer}
sessionInfo()
```

